spring.application.name=geoFields
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/geofields}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

server.servlet.session.timeout=120m
spring.cache.type=none

spring.session.store-type=redis
spring.session.redis.namespace=geofields:session


server.error.include-message=always

logging.level.web=INFO
logging.level.root=INFO
logging.level.sql=INFO
logging.level.com.geofields.service.NdviTileCacheService=INFO
logging.level.com.geofields.service.NdviTileFetchService=INFO
logging.level.com.geofields.service.NdviPythonClient=INFO
logging.level.com.geofields.controllers.NdviPythonProxyController=INFO

geofields.ndvi.python-base-url=${NDVI_PYTHON_BASE_URL:http://localhost:8001}

geofields.s3.enabled=${S3_ENABLED:true}
geofields.s3.endpoint=${S3_ENDPOINT:http://127.0.0.1:9000}
geofields.s3.access-key=${S3_ACCESS_KEY:minioadmin}
geofields.s3.secret-key=${S3_SECRET_KEY:minioadmin}
geofields.s3.bucket-tiles=${S3_BUCKET_TILES:geofields-tiles}
